### ISSUE TITLE
Current install mod state? (http removed?)

### ISSUE THREAD

**Issue by nicholasareed** [phoddie/runmod#3]
I noticed that the http server appears to have been removed in favor of websockets. I can't seem to get my moddable zero visible on the network (says `probe claimed runmod`) so that I can install a mod. Previously I was expecting to use simple browser requests ie `runmod.local/config/setName/mynewname`, but now I'm having trouble verifying runmod on the network (can't ping, doesnt show up in any mDNS discovery), and I noticed there are some hardcoded paths in the `html/` files. 

Just curious if it is a transition state and I ought to wait a few days! 

```
Wi-Fi connected to "HOME-4448"
IP address 10.0.0.2
/Users/nickreed/Projects/moddable/examples/experimental/runmod/main.js (37) # Break: require: module "mod" not found!
exception loading mod
host ready at runmod.local
probe for runmod
probe 1
probe 2
probe 3
probe claimed runmod
```

**Comment by phoddie** [comment]
Yes, HTTP support was removed. The reasoning is explained [here](https://github.com/phoddie/runmod/issues/1#issuecomment-488532380).

The previous code should still work. You can revert to [the commit right before](https://github.com/phoddie/runmod/commit/ca8d0aabccfb4f96a06f1581bfa11262cceac622) HTTP support was removed.

The mDNS support is unchanged, and verified to be working.
