### ISSUE TITLE
Graphics support (PIU)? 

### ISSUE THREAD

**Issue by nicholasareed** [phoddie/runmod#4]
I noticed that in the listed Built-In Modules (https://github.com/phoddie/runmod#host--built-in-modules) there doesn't appear to be graphics support. 

Is that an upcoming feature (or one I overlooked), or outside the current scope for runmod?

**Comment by phoddie** [comment]
A mod host needs to decide the features it wishes to support. This host does not provide a user interface framework or graphics library. You may add the Piu user interface framework to the [manifest](https://github.com/phoddie/runmod/blob/master/manifest.json#L2) trivially. That will also includes the fundamentals of Commodetto graphics.

	"include": [
		"$(MODDABLE)/examples/manifest_base.json",
		"$(MODDABLE)/examples/manifest_net.json",
		"$(MODULES)/network/mdns/manifest.json",
		"$(MODULES)/files/preference/manifest.json",
		"$(MODDABLE)/examples/manifest_piu.json",
	],

When building, you'll need a target device that includes a screen. For Moddable Zero, that is:
 
	mcconfig -d -m -p esp/moddable_zero
