### ISSUE TITLE
does it have a video tutorial? its quite difficult to understand for intermediate ESP32 user

### ISSUE THREAD

**Issue by imranaalam** [phoddie/runmod#9]
can you lead to some videos or starting material ( may be written or authored by someone else for some other purpose)

**Comment by phoddie** [comment]
Hello, @imranaalam. I'm glad you find the `runmod` work interesting. It is an important direction for us.

At this time the `runmod` work is very much an advanced topic right now and still considered experimental. Once it matures, we intend to integrate it into the Moddable SDK. At that time, additional materials will be provided to make it accessible to more developers.

Or perhaps I have misunderstood. Are you looking for general materials to help getting started with the Moddable SDK on ESP32?
